/*
 * This file is generated by jOOQ.
 */
package com.dribeho.database.jooq.tables.records;


import com.dribeho.database.jooq.tables.Images;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImagesRecord extends UpdatableRecordImpl<ImagesRecord> implements Record6<String, String, String, String, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>dribehodb.images.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>dribehodb.images.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>dribehodb.images.shop_id</code>.
     */
    public void setShopId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dribehodb.images.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dribehodb.images.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dribehodb.images.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dribehodb.images.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dribehodb.images.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dribehodb.images.date_uploaded</code>.
     */
    public void setDateUploaded(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>dribehodb.images.date_uploaded</code>.
     */
    public LocalDate getDateUploaded() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>dribehodb.images.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dribehodb.images.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, LocalDate, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, LocalDate, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Images.IMAGES.ID;
    }

    @Override
    public Field<String> field2() {
        return Images.IMAGES.SHOP_ID;
    }

    @Override
    public Field<String> field3() {
        return Images.IMAGES.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return Images.IMAGES.IMAGE_URL;
    }

    @Override
    public Field<LocalDate> field5() {
        return Images.IMAGES.DATE_UPLOADED;
    }

    @Override
    public Field<String> field6() {
        return Images.IMAGES.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getShopId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getImageUrl();
    }

    @Override
    public LocalDate component5() {
        return getDateUploaded();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getShopId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getImageUrl();
    }

    @Override
    public LocalDate value5() {
        return getDateUploaded();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public ImagesRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public ImagesRecord value2(String value) {
        setShopId(value);
        return this;
    }

    @Override
    public ImagesRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public ImagesRecord value4(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public ImagesRecord value5(LocalDate value) {
        setDateUploaded(value);
        return this;
    }

    @Override
    public ImagesRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ImagesRecord values(String value1, String value2, String value3, String value4, LocalDate value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImagesRecord
     */
    public ImagesRecord() {
        super(Images.IMAGES);
    }

    /**
     * Create a detached, initialised ImagesRecord
     */
    public ImagesRecord(String id, String shopId, String userId, String imageUrl, LocalDate dateUploaded, String description) {
        super(Images.IMAGES);

        setId(id);
        setShopId(shopId);
        setUserId(userId);
        setImageUrl(imageUrl);
        setDateUploaded(dateUploaded);
        setDescription(description);
    }
}
