openapi: "3.0.3"
info:
  title: DriBeHo API
  version: 1.0.0
components:
  schemas:
    Cafe:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zipcode:
          type: string
      required:
        - id
        - name
        - address
        - city
        - state
        - zipcode
    Review:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cafeId:
          type: string
          format: uuid
        rating:
          type: integer
        comment:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - userId
        - coffeeShopId
        - rating
        - createdAt
paths:
  /cafes:
    get:
      summary: Get a list of all cafes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cafe'
    post:
      summary: Create a new coffee shop
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cafe'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cafe'
  /reviews:
    get:
      summary: Get reviews for a cafe
      description: Retrieve a list of reviews for a specific cafe
      parameters:
        - name: cafe_id
          in: query
          description: The ID of the cafe to retrieve reviews for
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A list of reviews for the specified coffee shop
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
    post:
      summary: Create a new review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
