/*
 * This file is generated by jOOQ.
 */
package com.dribeho.database.jooq;


import com.dribeho.database.jooq.tables.Cafes;
import com.dribeho.database.jooq.tables.FlywaySchemaHistory;
import com.dribeho.database.jooq.tables.Quarkus;


/**
 * Convenience access to all tables in dribehodb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dribehodb.cafes</code>.
     */
    public static final Cafes CAFES = Cafes.CAFES;

    /**
     * The table <code>dribehodb.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>dribehodb.quarkus</code>.
     */
    public static final Quarkus QUARKUS = Quarkus.QUARKUS;
}
