/*
 * This file is generated by jOOQ.
 */
package com.dribeho.database.jooq.tables;


import com.dribeho.database.jooq.Dribehodb;
import com.dribeho.database.jooq.Indexes;
import com.dribeho.database.jooq.Keys;
import com.dribeho.database.jooq.tables.records.ImagesRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Images extends TableImpl<ImagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dribehodb.images</code>
     */
    public static final Images IMAGES = new Images();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImagesRecord> getRecordType() {
        return ImagesRecord.class;
    }

    /**
     * The column <code>dribehodb.images.id</code>.
     */
    public final TableField<ImagesRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>dribehodb.images.shop_id</code>.
     */
    public final TableField<ImagesRecord, String> SHOP_ID = createField(DSL.name("shop_id"), SQLDataType.VARCHAR(36).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dribehodb.images.user_id</code>.
     */
    public final TableField<ImagesRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(36).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dribehodb.images.image_url</code>.
     */
    public final TableField<ImagesRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>dribehodb.images.date_uploaded</code>.
     */
    public final TableField<ImagesRecord, LocalDate> DATE_UPLOADED = createField(DSL.name("date_uploaded"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>dribehodb.images.description</code>.
     */
    public final TableField<ImagesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    private Images(Name alias, Table<ImagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Images(Name alias, Table<ImagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>dribehodb.images</code> table reference
     */
    public Images(String alias) {
        this(DSL.name(alias), IMAGES);
    }

    /**
     * Create an aliased <code>dribehodb.images</code> table reference
     */
    public Images(Name alias) {
        this(alias, IMAGES);
    }

    /**
     * Create a <code>dribehodb.images</code> table reference
     */
    public Images() {
        this(DSL.name("images"), null);
    }

    public <O extends Record> Images(Table<O> child, ForeignKey<O, ImagesRecord> key) {
        super(child, key, IMAGES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Dribehodb.DRIBEHODB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IMAGES_SHOP_ID, Indexes.IMAGES_USER_ID);
    }

    @Override
    public UniqueKey<ImagesRecord> getPrimaryKey() {
        return Keys.KEY_IMAGES_PRIMARY;
    }

    @Override
    public List<ForeignKey<ImagesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.IMAGES_IBFK_1, Keys.IMAGES_IBFK_2);
    }

    private transient Cafes _cafes;
    private transient Users _users;

    /**
     * Get the implicit join path to the <code>dribehodb.cafes</code> table.
     */
    public Cafes cafes() {
        if (_cafes == null)
            _cafes = new Cafes(this, Keys.IMAGES_IBFK_1);

        return _cafes;
    }

    /**
     * Get the implicit join path to the <code>dribehodb.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.IMAGES_IBFK_2);

        return _users;
    }

    @Override
    public Images as(String alias) {
        return new Images(DSL.name(alias), this);
    }

    @Override
    public Images as(Name alias) {
        return new Images(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Images rename(String name) {
        return new Images(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Images rename(Name name) {
        return new Images(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, LocalDate, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
